apiVersion: v1
kind: Secret
metadata:
  name: fiap-lanches-secret
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: mysecretpassword
  POSTGRES_USER: postgres
  POSTGRES_HOST: svc-postgres
